### ISSUE TITLE
error when installing app using an eddi 2.1

### ISSUE THREAD

**Issue by GBurchel** [VeloWulf/myenergiIntegration#1]
not really sure whats going on but this is the log from when i try to install

[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.723[error](http://192.168.1.154/logs#)java.lang.NullPointerException: Cannot get property 'size' on null object on line 132 (method devicePage)
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.704[debug](http://192.168.1.154/logs#)eddiMap = null
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.701[debug](http://192.168.1.154/logs#)Exception in pollASNServer call: status code: 401, reason phrase: Unauthorized
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.508[debug](http://192.168.1.154/logs#)Auth Command parameters = [uri:https://s18.myenergi.net, path:/cgi-jstatus-*, contentType:application/json, timeout:300, headers:[Authorization:Digest username="Garyburchell@outlook.com", realm="MyEnergi Telemetry", qop="auth", algorithm="MD5", uri="/cgi-jstatus-*", nonce="3SIt5cFk0AdQ1w2Q3ZUlfcxFHOstBJOa", cnonce="9bff44f7", opaque="78b66b1db9dc49dd845535e7d7b35287", nc=2, response="dd8e1c93e4ef184a1136397b96aac984"]]
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.505[debug](http://192.168.1.154/logs#)Response: dd8e1c93e4ef184a1136397b96aac984 ===== orig:b125d8fd66b85d0604385041ff88bc65:3SIt5cFk0AdQ1w2Q3ZUlfcxFHOstBJOa:2:9bff44f7:auth:c7c16c211e1f3baebe0175a6590ff345
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.498[debug](http://192.168.1.154/logs#)HA2: c7c16c211e1f3baebe0175a6590ff345 ===== orig:GET:/cgi-jstatus-*
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.495[debug](http://192.168.1.154/logs#)HA1: b125d8fd66b85d0604385041ff88bc65 ===== orig:Garyburchell@outlook.com:MyEnergi Telemetry:F34zdnet
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.484[trace](http://192.168.1.154/logs#)Running calcDigest
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.481[debug](http://192.168.1.154/logs#)Auth Map = [realm:MyEnergi Telemetry, nonce:3SIt5cFk0AdQ1w2Q3ZUlfcxFHOstBJOa, opaque:78b66b1db9dc49dd845535e7d7b35287, algorithm:MD5, qop:auth]
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.478[debug](http://192.168.1.154/logs#)Authorization = Digest realm="MyEnergi Telemetry", nonce="3SIt5cFk0AdQ1w2Q3ZUlfcxFHOstBJOa", opaque="78b66b1db9dc49dd845535e7d7b35287", algorithm=MD5, qop="auth"
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.474[debug](http://192.168.1.154/logs#)AuthMap Response Headers = [Date: Wed, 30 Nov 2022 08:53:09 GMT, Content-Length: 0, Connection: keep-alive, Access-Control-Expose-Headers: Server-Timing, Server-Timing: traceparent;desc="00-ad1e9430854676ff8419e7585dfa6cb9-e2973ee2579d0535-01", X-Content-Type-Options: nosniff, X-DNS-Prefetch-Control: off, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-XSS-Protection: 1; mode=block, Strict-Transport-Security: max-age=15552000; includeSubDomains, WWW-Authenticate: Digest realm="MyEnergi Telemetry", nonce="3SIt5cFk0AdQ1w2Q3ZUlfcxFHOstBJOa", opaque="78b66b1db9dc49dd845535e7d7b35287", algorithm=MD5, qop="auth", x_myenergi-asn: undefined, Access-Control-Allow-Credentials: true, Access-Control-Allow-Headers: Origin, Content-Type, Accept, Cookie, Access-Control-Allow-Origin: https://admin-ui.s18.myenergi.net]
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.463[debug](http://192.168.1.154/logs#)AuthMap Response Status = 401
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.240[debug](http://192.168.1.154/logs#)LatestASN = s18.myenergi.net
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.237[debug](http://192.168.1.154/logs#)AuthMap Response Headers = [Date: Wed, 30 Nov 2022 08:53:08 GMT, Content-Length: 0, Connection: keep-alive, Access-Control-Expose-Headers: Server-Timing, Server-Timing: traceparent;desc="00-3f3dad88f1efa9f8ea6a68493ac3a442-c9f86593329cbea5-01", X-Content-Type-Options: nosniff, X-DNS-Prefetch-Control: off, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-XSS-Protection: 1; mode=block, Strict-Transport-Security: max-age=15552000; includeSubDomains, WWW-Authenticate: Digest realm="MyEnergi Telemetry", nonce="xfqmmPCea4OpVShJTg1CXXS4kbySn1pT", opaque="78b66b1db9dc49dd845535e7d7b35287", algorithm=MD5, qop="auth", x_myenergi-asn: s18.myenergi.net, Access-Control-Allow-Credentials: true, Access-Control-Allow-Headers: Origin, Content-Type, Accept, Cookie, Access-Control-Allow-Origin: https://admin-ui.s18.myenergi.net]
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.226[debug](http://192.168.1.154/logs#)AuthMap Response Status = 401
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.026[debug](http://192.168.1.154/logs#)Auth Command parameters = [uri:https://director.myenergi.net, path:/cgi-jstatus-*, headers:[Authorization:Digest username="Garyburchell@outlook.com", realm="MyEnergi Telemetry", qop="auth", algorithm="MD5", uri="/cgi-jstatus-*", nonce="OYUpXZq6c8ky2694kgo4ojVQOfwE7gP7", cnonce="70838d99", opaque="78b66b1db9dc49dd845535e7d7b35287", nc=1, response="6d907af9c070210f871d4747bb5e1e51"]]
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.022[debug](http://192.168.1.154/logs#)Response: 6d907af9c070210f871d4747bb5e1e51 ===== orig:b125d8fd66b85d0604385041ff88bc65:OYUpXZq6c8ky2694kgo4ojVQOfwE7gP7:1:70838d99:auth:c7c16c211e1f3baebe0175a6590ff345
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.019[debug](http://192.168.1.154/logs#)HA2: c7c16c211e1f3baebe0175a6590ff345 ===== orig:GET:/cgi-jstatus-*
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.016[debug](http://192.168.1.154/logs#)HA1: b125d8fd66b85d0604385041ff88bc65 ===== orig:Garyburchell@outlook.com:MyEnergi Telemetry:F34zdnet
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.013[trace](http://192.168.1.154/logs#)resetting nc
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.011[trace](http://192.168.1.154/logs#)Running calcDigest
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.008[trace](http://192.168.1.154/logs#)Adding auth header
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.005[debug](http://192.168.1.154/logs#)Auth Map = [realm:MyEnergi Telemetry, nonce:OYUpXZq6c8ky2694kgo4ojVQOfwE7gP7, opaque:78b66b1db9dc49dd845535e7d7b35287, algorithm:MD5, qop:auth]
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:13.002[debug](http://192.168.1.154/logs#)Authorization = Digest realm="MyEnergi Telemetry", nonce="OYUpXZq6c8ky2694kgo4ojVQOfwE7gP7", opaque="78b66b1db9dc49dd845535e7d7b35287", algorithm=MD5, qop="auth"
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:12.999[debug](http://192.168.1.154/logs#)AuthMap Response Headers = [Date: Wed, 30 Nov 2022 08:53:08 GMT, Content-Length: 0, Connection: keep-alive, Access-Control-Expose-Headers: Server-Timing, Server-Timing: traceparent;desc="00-d3a53f331745097b74d2b760c53fd54d-3373342d796a3f4a-01", X-Content-Type-Options: nosniff, X-DNS-Prefetch-Control: off, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-XSS-Protection: 1; mode=block, Strict-Transport-Security: max-age=15552000; includeSubDomains, WWW-Authenticate: Digest realm="MyEnergi Telemetry", nonce="OYUpXZq6c8ky2694kgo4ojVQOfwE7gP7", opaque="78b66b1db9dc49dd845535e7d7b35287", algorithm=MD5, qop="auth", x_myenergi-asn: undefined, Access-Control-Allow-Credentials: true, Access-Control-Allow-Headers: Origin, Content-Type, Accept, Cookie, Access-Control-Allow-Origin: https://admin-ui.s18.myenergi.net]
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:12.988[debug](http://192.168.1.154/logs#)AuthMap Response Status = 401
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:12.742[trace](http://192.168.1.154/logs#)Running getASN
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:12.739[trace](http://192.168.1.154/logs#)Obtaining current asn server
[app:4195](http://192.168.1.154/logs#)2022-11-30 08:53:12.736[trace](http://192.168.1.154/logs#)Running getDeviceList

**Comment by VeloWulf** [comment]
https://community.hubitat.com/t/release-myenergi-integration/81029/11?u=velowulf
